# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/market_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schema/market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18schema/market_data.proto\x12\x06schema\"|\n\nMarketData\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\tbid_price\x18\x03 \x01(\x01\x12\x11\n\task_price\x18\x04 \x01(\x01\x12\x10\n\x08\x62id_size\x18\x05 \x01(\x01\x12\x10\n\x08\x61sk_size\x18\x06 \x01(\x01\"w\n\x0bTradeSignal\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\x01\x12\r\n\x05price\x18\x05 \x01(\x01\x12\x15\n\rstrategy_name\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKETDATA']._serialized_start=36
  _globals['_MARKETDATA']._serialized_end=160
  _globals['_TRADESIGNAL']._serialized_start=162
  _globals['_TRADESIGNAL']._serialized_end=281
# @@protoc_insertion_point(module_scope)
