from prometheus_client import start_http_server, Counter, Histogram, Gauge

messages_produced = Counter('messages_produced_total', 'Total market data messages produced')
messages_consumed = Counter('messages_consumed_total', 'Total market data messages consumed')
signals_generated = Counter('signals_generated_total', 'Total trade signals generated by strategies', ['strategy', 'action', 'symbol'])
process_latency = Histogram('process_latency_seconds', 'Time taken to process message pipeline', ['operation'])
obi_gauge = Gauge('obi_value', 'Order Book Imbalance', ['symbol'])
micro_price_gauge = Gauge('micro_price', 'Micro Price', ['symbol'])


def start_metrics_server(port: int = 8000):
    start_http_server(port)
